version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  cypress-run:
    docker:
      - image: cypress/base:12.18.3
    steps:
      - checkout
      - cypress/install
      - cypress/run

workflows:
  version: 2
  cypress-workflow:
    jobs:
      - cypress-run
